"use client";

import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";

const testimonials = [
  {
    name: "Emad",
    Avatar: "A",
    title: "Software Engineer",
    description: "this is the best application i have used ",
  },
  {
    name: "Sara",
    Avatar: "S",
    title: "Graphic Designer",
    description: "Emad AI helped me create a stunning Images for my work",
  },
  {
    name: "Magnus Carlesen",
    Avatar: "A",
    title: "Web Developer",
    description: "the code generated by this app helped me save a lot of time",
  },
  {
    name: "Diana olson",
    Avatar: "A",
    title: "Animator",
    description: "the sound effects generated with Emad AI is  mind blowing",
  },
 
];

const Testimonials = () => {
  return (
    <div className="px-10 pb-20">
      <h2 className="text-center text-4xl text-white font-extrabold mb-10">
        Testimonials
      </h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {testimonials.map((item) => (
          <Card
            key={item.description}
            className="bg-[#192339] border-none text-white"
          >
            <CardHeader>
              <CardTitle className=" items-center gap-x-2">
                <p className="text-lg">{item.name}</p>
                <p className="text-zinc-400 text-sm">{item.title}</p>
              </CardTitle>
            </CardHeader>

            <CardContent>
                {item.description}
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default Testimonials;
